name: Push to demo

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Rename files
      run: |
        mv src/routes/(public)/+page.svelte src/routes/(public)/normal_page.svelte
        mv src/routes/(public)/page_demo.svelte src/routes/(public)/+page.svelte

    - name: Push to demo
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git checkout -b demo
        git add .
        git commit -m "Auto push to demo"
        git push origin demo --force